spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/Spring_study/jpashop_DB
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
